import 'package:FUS/router/router.dart';
import 'package:FUS/widget/appbar_widget.dart';
import 'package:FUS/widget/list_view_item.dart';
import 'package:flutter/material.dart';

class FlutterWidgetPage extends StatefulWidget {
  @override
  _FlutterWidgetPageState createState() => _FlutterWidgetPageState();
}

class _FlutterWidgetPageState extends State<FlutterWidgetPage> {
  List<ListItemModel> _list = List();

  @override
  void initState() {
    super.initState();
    _list = [
      ListItemModel('Canvas', () => Router.toPage(context, 'canvasPage')),
      ListItemModel('Container', () {}),
      ListItemModel('Row', () {}),
      ListItemModel('Column', () {}),
      ListItemModel('Stack', () {}),
      ListItemModel('ListView', () {}),
      ListItemModel('Image', () {}),
      ListItemModel('Text', () {}),
      ListItemModel('Icon', () {}),
      ListItemModel('RaisedButton', () {}),
      ListItemModel('Scaffold', () {}),
      ListItemModel('Appbar', () {}),
      ListItemModel('FlutterLogo', () {}),
      ListItemModel('Placeholder', () {}),
      ListItemModel('AnimatedAlign', () {}),
      ListItemModel('AnimatedBuilder', () {}),
      ListItemModel('AnimatedContainer', () {}),
      ListItemModel('AnimatedCrossFade', () {}),
      ListItemModel('AnimatedDefaultTextStyle', () {}),
      ListItemModel('AnimatedListState', () {}),
      ListItemModel('AnimatedModalBarrier', () {}),
      ListItemModel('AnimatedOpacity', () {}),
      ListItemModel('AnimatedPhysicalModel', () {}),
      ListItemModel('AnimatedPosition', () {}),
      ListItemModel('AnimatedSize', () {}),
      ListItemModel('AnimatedWidget', () {}),
      ListItemModel('AnimatedWidgetBaseState', () {}),
      ListItemModel('DecoratedBoxTransition', () {}),
      ListItemModel('FadeTransition', () {}),
      ListItemModel('Hero', () {}),
      ListItemModel('PositionedTransition', () {}),
      ListItemModel('RotationTransition', () {}),
      ListItemModel('ScaleTransition', () {}),
      ListItemModel('SizeTansition', () {}),
      ListItemModel('SlideTransition', () {}),
      ListItemModel('AssetBundle', () {}),
      ListItemModel('RawImage', () {}),
      ListItemModel('FutureBuilder', () {}),
      ListItemModel('SteamBuilder', () {}),
      ListItemModel('CupertinoActionSheet', () {}),
      ListItemModel('CupertinoActivityIndicator', () {}),
      ListItemModel('CupertinoAlertDialog', () {}),
      ListItemModel('CupertinoButton', () {}),
      ListItemModel('CupertinoContextMenu', () {}),
      ListItemModel('CupertinoDatePicker', () {}),
      ListItemModel('CupertinoDialog', () {}),
      ListItemModel('CupertinoDialogAction', () {}),
      ListItemModel('CupertinoFullscreenDialogTransition', () {}),
      ListItemModel('CupertinoNavigationBar', () {}),
      ListItemModel('CupertinoPageScaffold', () {}),
      ListItemModel('CupertinoPageTransition', () {}),
      ListItemModel('CupertinoPicker', () {}),
      ListItemModel('CupertinoPopupSurface', () {}),
      ListItemModel('CupertinoScrollbar', () {}),
      ListItemModel('CupertinoSegmentedControl', () {}),
      ListItemModel('CupertinoSlider', () {}),
      ListItemModel('CupertinoSlidingSegmentedControl', () {}),
      ListItemModel('CupertinoSwitch', () {}),
      ListItemModel('CupertinoTabBar', () {}),
      ListItemModel('CupertinoCupertinoTabScaffold', () {}),
      ListItemModel('CupertinoTabView', () {}),
      ListItemModel('CupertinoTextField', () {}),
      ListItemModel('CupertinoTimerPicker', () {}),
      ListItemModel('Form', () {}),
      ListItemModel('FormField', () {}),
      ListItemModel('RawKeyboardListener', () {}),
      ListItemModel('AbsorbPointer', () {}),
      ListItemModel('Dismissible', () {}),
      ListItemModel('DragTarget', () {}),
      ListItemModel('Draggable', () {}),
      ListItemModel('GestureDetector', () {}),
      ListItemModel('IgnorePointer', () {}),
      ListItemModel('LongPressDraggable', () {}),
      ListItemModel('Scrollable', () {}),
      ListItemModel('Align', () {}),
      ListItemModel('AspectRatio', () {}),
      ListItemModel('Baseline', () {}),
      ListItemModel('Center', () {}),
      ListItemModel('ConstrainedBox', () {}),
      ListItemModel('CustomSingleChildLayout', () {}),
      ListItemModel('Expanded', () {}),
      ListItemModel('FittedBox', () {}),
      ListItemModel('FractionallySizedBox', () {}),
      ListItemModel('IntrinsicHeight', () {}),
      ListItemModel('IntrinsicWidth', () {}),
      ListItemModel('LimitedBox', () {}),
      ListItemModel('Offstage', () {}),
      ListItemModel('OverflowBox', () {}),
      ListItemModel('Padding', () {}),
      ListItemModel('SizedBox', () {}),
      ListItemModel('SizedOverflowBox', () {}),
      ListItemModel('Transform', () {}),
      ListItemModel('CustomMultiChildLayout', () {}),
      ListItemModel('Flow', () {}),
      ListItemModel('GridView', () {}),
      ListItemModel('IndexedStack', () {}),
      ListItemModel('LayoutBuilder', () {}),
      ListItemModel('ListBody', () {}),
      ListItemModel('Table', () {}),
      ListItemModel('Wrap', () {}),
      ListItemModel('BottomNavigationBar', () {}),
      ListItemModel('Drawer', () {}),
      ListItemModel('MaterialApp', () {}),
      ListItemModel('SliverAppBar', () {}),
      ListItemModel('TabBar', () {}),
      ListItemModel('TabBarView', () {}),
      ListItemModel('WidgetsApp', () {}),
      ListItemModel('ButtonBar', () {}),
      ListItemModel('DropdownButton', () {}),
      ListItemModel('FlatButton', () {}),
      ListItemModel('FloatingActionButton', () {}),
      ListItemModel('IconButton', () {}),
      ListItemModel('OutlineButton', () {}),
      ListItemModel('PopupMenuButton', () {}),
      ListItemModel('Checkbox', () {}),
      ListItemModel('Date&time Pickers', () {}),
      ListItemModel('Radio', () {}),
      ListItemModel('Slider', () {}),
      ListItemModel('Switch', () {}),
      ListItemModel('TextField', () {}),
      ListItemModel('AlertDialog', () {}),
      ListItemModel('BottomSheet', () {}),
      ListItemModel('SimpleDialog', () {}),
      ListItemModel('SnackBar', () {}),
      ListItemModel('Card', () {}),
      ListItemModel('Chip', () {}),
      ListItemModel('CircularProgressIndicator', () {}),
      ListItemModel('DataTable', () {}),
      ListItemModel('LinearProgressIndicator', () {}),
      ListItemModel('Tooltip', () {}),
      ListItemModel('Divider', () {}),
      ListItemModel('ListTile', () {}),
      ListItemModel('Stepper', () {}),
      ListItemModel('BackdropFilter', () {}),
      ListItemModel('ClipOval', () {}),
      ListItemModel('ClipPath', () {}),
      ListItemModel('ClipRect', () {}),
      ListItemModel('CustomPaint', () {}),
      ListItemModel('DecoratedBox', () {}),
      ListItemModel('FractionalTranslation', () {}),
      ListItemModel('Opacity', () {}),
      ListItemModel('RotatrdBox', () {}),
      ListItemModel('CustomScrollView', () {}),
      ListItemModel('NestedScrollView', () {}),
      ListItemModel('NotificationListener', () {}),
      ListItemModel('RefreshIndicator', () {}),
      ListItemModel('ScrollConfiguration', () {}),
      ListItemModel('Scrollbar', () {}),
      ListItemModel('SingleChildScrollView', () {}),
      ListItemModel('MediQuery', () {}),
      ListItemModel('Theme', () {}),
      ListItemModel('DefaultTextStyle', () {}),
      ListItemModel('RichText', () {}),
    ];
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBarWidget('Flutter Widget', context),
      body: ListView.builder(
        itemCount: _list.length,
        itemBuilder: (BuildContext ctx, int i) => ListViewItem(_list[i]),
      ),
    );
  }
}

